apiVersion: v1
kind: Service
metadata:
  name: platform-lab-service

spec:
  type: NodePort

  selector:
    app: platform-lab-app

  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080